// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistrationJavaGuruTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registrationJavaGuru() {
    driver.get("https://www.google.com/search?q=JavaGuru&sca_esv=599466310&sxsrf=ACQVn0_BomprRKAYypN8EgDYyDk7zzeTgg%3A1705586296514&source=hp&ei=eC6pZeTgHPWQxc8PrsCMqAw&iflsig=ANes7DEAAAAAZak8iLFMd8laMZPIyXcpIEhzHqXjdKYj&udm=&ved=0ahUKEwjk_NaKjOeDAxV1SPEDHS4gA8UQ4dUDCA0&uact=5&oq=JavaGuru&gs_lp=Egdnd3Mtd2l6IghKYXZhR3VydTIEECMYJzIQEC4YgAQYFBiHAhjHARivATIEEAAYHjICECZI7x1QAFj8GXAAeACQAQCYAWWgAcsEqgEDNy4xuAEDyAEA-AEBwgIEEC4YJ8ICEBAuGIAEGIoFGEMYxwEYrwHCAgoQABiABBiKBRhDwgIIEAAYgAQYsQPCAgsQABiABBixAxiDAcICFBAuGIAEGLEDGMcBGK8BGJgFGJkFwgIQEAAYgAQYigUYQxixAxiDAcICDxAAGAEYgAQYsQMYgwEYCsICCxAuGIAEGLEDGIMBwgIFEAAYgATCAgUQLhiABMICCxAuGIAEGMcBGNEDwgIHEAAYgAQYCsICEBAuGBQYrwEYxwEYhwIYgATCAgYQABgeGAo&sclient=gws-wiz");
    driver.manage().window().setSize(new Dimension(1382, 744));
    {
      WebElement element = driver.findElement(By.cssSelector(".CCgQ5 > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".CCgQ5 > span")).click();
    driver.findElement(By.cssSelector(".header-button > .default-button")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".header-button > .default-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.name("form-name")).click();
    driver.findElement(By.name("form-name")).sendKeys("nnbvc");
    driver.findElement(By.name("form-surname")).click();
    driver.findElement(By.name("form-surname")).sendKeys("lkjg");
    driver.findElement(By.name("form-email")).click();
    driver.findElement(By.name("form-email")).sendKeys("ljhfd");
    driver.findElement(By.name("form-phone")).click();
    driver.findElement(By.name("form-phone")).sendKeys("6789");
    driver.findElement(By.cssSelector(".selectric-course-input .label")).click();
    driver.findElement(By.cssSelector(".selectric-scroll li:nth-child(6)")).click();
    driver.findElement(By.name("form-message")).click();
    driver.findElement(By.name("form-message")).sendKeys("text");
    driver.findElement(By.cssSelector(".close-popup-cross")).click();
    driver.findElement(By.cssSelector(".submit-button > .default-button")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".submit-button > .default-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
